version: "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 55432:5432
    networks:
      - blog-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:5050
    networks:
      - blog-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - db
    networks:
      - blog-network

  weave-scope:
    image: weaveworks/scope:1.13.2
    container_name: weave-scope
    privileged: true
    pid: "host"
    ports:
      - "4040:4040"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
    networks:
      - blog-network
    command:
      - "--probe.docker=true"
      - "--probe.docker.bridge=docker0"
      - "--weave=false"  # Désactive l'intégration avec Weave Net
    labels:
      - "com.docker.compose.project=blog"
      - "com.docker.compose.service=weave-scope"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - blog-network

  locust:
    image: locustio/locust
    container_name: locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/locustfile.py
    command: locust -f /locustfile.py --host=http://nginx
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
